#include "odo.h"
#include "config.h"
#include "hardware/pio.h"
#include "quadrature_encoder.pio.h"   // generated by pico_generate_pio_header

// Front encoder on PIO0, state machine 0. A/B must be consecutive GPIOs
// (A = FRONT_ENCODER_A_PIN, B = A+1); config uses GP10/GP11.
static PIO  s_pio = pio0;
static uint s_sm  = 0;
static long s_zero = 0;

void odoInit() {
  pio_add_program(s_pio, &quadrature_encoder_program);
  // last arg 0 = max count rate (0 -> as fast as possible), same as robotour
  quadrature_encoder_program_init(s_pio, s_sm, FRONT_ENCODER_A_PIN, 0);
}

long odoCountRaw() {
  return quadrature_encoder_get_count(s_pio, s_sm);
}

void odoZero() {
  s_zero = odoCountRaw();
}

float odoDistanceM() {
  // NOTE: M_PER_COUNT must be calibrated (config.h) — it is 0.0 until you do,
  // which will (intentionally) read 0 distance and make the miscalibration obvious.
  return (float)(odoCountRaw() - s_zero) * M_PER_COUNT;
}

float odoDistanceCm() {
  return odoDistanceM() * 100.0f;
}
